import writeChangeset from "@changesets/write";
import type { PublicChangedPackage, DependencyChange } from "./types";

/**
 * Generate npm package URL
 */
function getNpmPackageUrl(packageName: string): string {
  return `https://www.npmjs.com/package/${packageName}`;
}

/**
 * Generate a single line summary for a single dependency change
 */
function generateSingleLineSummary(change: DependencyChange): string {
  const link = `[${change.name}](${getNpmPackageUrl(change.name)})`;
  switch (change.type) {
    case "updated":
      return `Updated ${link} (${change.oldVersion} -> ${change.newVersion})`;
    case "added":
      return `Added ${link} (${change.newVersion})`;
    case "removed":
      return `Removed ${link} (${change.oldVersion})`;
  }
}

/**
 * Auto-generated banner comment for changesets
 */
export const AUTO_GENERATED_BANNER = `<!-- This changeset was auto-generated by deps2changesets -->`;

/**
 * Generate a human-readable summary from dependency changes
 * @param changes - Non-empty array of dependency changes (empty array is not expected)
 */
function generateSummaryFromChanges(changes: DependencyChange[]): string {
  let content: string;
  if (changes.length === 1) {
    // Single change: return a single line without heading
    content = generateSingleLineSummary(changes[0]);
  } else {
    // Use markdown list format with heading for multiple changes
    content = [
      "Dependencies updated\n",
      ...changes.map((c) => `- ${generateSingleLineSummary(c)}`),
    ].join("\n");
  }

  return `${content}\n\n${AUTO_GENERATED_BANNER}`;
}

/**
 * Result of creating a single changeset
 */
export interface ChangesetResult {
  /** The changeset ID */
  id: string;
}

/**
 * Create changesets for changed packages
 * @returns Array of created changesets
 */
export async function createChangesets(
  changedPackages: PublicChangedPackage[],
  releaseType: "patch" | "minor" | "major",
  cwd: string
): Promise<ChangesetResult[]> {
  if (changedPackages.length === 0) {
    return [];
  }

  const results: ChangesetResult[] = [];

  for (const changedPackage of changedPackages) {
    const packageName = changedPackage.package.packageJson.name;

    const summary = generateSummaryFromChanges(
      changedPackage.dependencyChanges
    );

    const changesetId = await writeChangeset(
      {
        summary,
        releases: [
          {
            name: packageName,
            type: releaseType,
          },
        ],
      },
      cwd
    );

    results.push({
      id: changesetId,
    });
  }

  return results;
}
